---
- name: Install needed packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: common_packages

- name: Install NTP
  apt: name=ntp state=present update_cache=yes

- name: Adding Swapfile
  include: swap.yml
  when: common_swap == True
